mandusm/aws-modernization-workshop

README.adoc
_modules.yml
modules/container-orchestration/readme.adoc
workshops/modernization-august-2018.yml

**Why:**
* This will allow both @CarmenAPuccio and I to add our content
in-parallal
* closes #13

#13 : Adding Base Module With Lorum Ipsum

---

_modules.yml
modules/artifactory/artifactory.json
modules/artifactory/readme.adoc
workshops/modernization-august-2018.yml

Adding Artifactory Module template and sample readme

---

modules/container-orchestration/petstore-fargate-task-definition.json
modules/container-orchestration/readme.adoc

Why:
This is the userguide for the Fargate Lab Walkthrough. 
Signed-off-by: Carmen A. Puccio <carmenpuccio@yahoo.com>

Adding the Fargate Lab Walkthrough

---

modules/container-orchestration/petstore-fargate-task-definition.json
modules/containerize-application/Dockerfile
modules/containerize-application/docker-compose.yml
modules/containerize-application/docker-entrypoint.sh
modules/containerize-application/standalone.xml

Why:
Various cleanup fixes and performance addressed in Fargate. This is an update to #3 and #4
Signed-off-by: Carmen A. Puccio carmenpuccio@yahoo.com

Container Cleanup Fixes

---

.gitignore
modules/container-orchestration/readme.adoc
modules/containerize-application/readme.adoc

**Why:**
* Make the workshoper output a little cleaner and allows a better UX
* closes #38

Fixing up the ASCIIDoc Formatting

---

modules/containerize-application/readme.adoc
modules/monitor-application/container/Dockerfile
modules/monitor-application/container/docker-compose.yml
modules/monitor-application/readme.adoc
modules/monitor-application/task-definition/petstore-fargate-task-definition.json

Why:
Adding support for Docker/Container Healthchecks. This lays the groundwork for #10 
Signed-off-by: Carmen A. Puccio carmenpuccio@yahoo.com

Puccio monitoring module

---

modules/containerize-application/readme.adoc

Fixes #42 More asciidoc formatting

---

modules/monitor-application/readme.adoc

Why:
This should be the full portion of the Docker, Amazon ECS/Fargate Monitoring and Logging Instructions for #10 
Still need to do this for EKS/K8s
Signed-off-by: Carmen A. Puccio <carmenpuccio@yahoo.com>

Docker, Amazon ECS/Fargate Monitoring and Logging Instructions.

---

modules/container-orchestration/petstore-eks-manifest.yaml
modules/container-orchestration/readme.adoc

**Why:**
* Adding the Kubernetes module for deploying the petstorw
* closes #15

Adding EKS & K8s Section

---

modules/container-orchestration/readme.adoc

Why:
Cleaning up the lab instructions. Some typos in the examples.
Signed-off-by: Carmen A. Puccio <carmenpuccio@yahoo.com>

Task definition example was wrong and some typos in the lab

---

modules/container-orchestration/readme.adoc

Noticed a typo for petstore_frontend in the steps.

Fixing typo in the steps.

---

modules/getting-started/readme.adoc

Update IAM Instance Profile Order

---

modules/artifactory/readme.adoc
modules/container-orchestration/readme.adoc
modules/containerize-application/readme.adoc
modules/getting-started/readme.adoc

Issue with one of the commands. Switching to [source,shell]

Quick Cleanup - command didn't copy

---

_modules.yml
modules/feedback/readme.adoc
modules/security/readme.adoc
workshops/modernization-august-2018.yml

Adding Source and Feedback Module

---

modules/artifactory/readme.adoc
modules/cicd/readme.adoc

issue #93 - updating artifactory and cicd

---

buildspec.yml

adding artifact path to buildspec

---

buildspec.yml

updated buildspec.yml to meet spec

---

modules/cicd/readme.adoc

add correct path to step 1

---

modules/container-orchestration-ecs/readme.adoc

Lots of typos found in the Workshop. Demo'ing modernization pull/push

Fixing Typos Live

---

modules/containerize-application/app/pom.xml

introduce vulnerability back to pom.xml

---

modules/containerize-application/readme.adoc

Fixes #130 
Changes spelling from `applicaiton` to `application`

Fix spelling of application

---

modules/cicd/readme.adoc

to avoid confusion during the workshop

coded some paths a little harder

---

modules/create-environment/readme.adoc
modules/create-environment/templates/workshop_env_master.yaml

update s3 path

---

modules/create-environment/readme.adoc

remove encoded slash
